name: Rust

on:
  - push
  - pull_request
  - merge_group

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}
  PROJECT_NAME: babelfont
  CARGO_PUBLISH_ARGS: ""
  CRATE_PATTERN: "babelfont"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching
      - name: Build
        run: cargo build
      - name: Check out notocjk for testing
        run: cd babelfont ; git clone https://github.com/notofonts/noto-cjk-varco.git --depth 1
      - name: Run tests
        run: |
          cargo test --verbose --workspace

  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching

      - name: Lint for formatting
        run: cargo fmt --all -- --check
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install protobuf-compiler
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Set up Rust for caching
      - name: Lint for warnings
        run: cargo clippy --all-targets --all-features -- -D warnings

  check-for-release:
    name: Create release if needed
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - if: contains(github.ref, 'refs/tags/v')
        run: python3 scripts/check_versions.py
        env:
          CRATE_PATTERN: ${{ env.CRATE_PATTERN }}
      - if: contains(github.ref, 'refs/tags/v')
        name: Check for release
        id: create_release
        run: |
          if ! gh release view ${{ github.ref_name }}; then
          git show -s --format=%B ${{ github.ref_name }} | tail -n +4 | gh release create ${{ github.ref_name }} -t ${{ github.ref_name }} -F -
          fi
